# Generated by Django 6.0.6 on 2026-07-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SesionProcesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_original', models.CharField(max_length=255)),
                ('imagen_resultado', models.CharField(blank=True, default='', max_length=255)),
                ('preset', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('cargando', 'Cargando modelo'), ('completado', 'Completado'), ('error', 'Error'), ('abortado', 'Abortado')], default='pendiente', max_length=20)),
                ('error_mensaje', models.TextField(blank=True, default='')),
                ('intentos_api', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
